[package]
name = "raees/newfrunze"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = 'sleitnick/knit@1.4.7'
Component = 'sleitnick/component@2.4.5'
Maid = "flamenco687/maid@3.2.2"
Signal = "sleitnick/signal@1.2.0"
Thread = "afrxo/thread@1.0.0"
Janitor = "howmanysmall/janitor@1.14.1"